CREATE TABLE [dbo].[ClientEntities] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [Name]                 NVARCHAR (MAX) NULL,
    [TIN]                  NVARCHAR (MAX) NULL,
    [Office_Address]       NVARCHAR (MAX) NULL,
    [Warehouse_Address]    NVARCHAR (MAX) NULL,
    [Credit_Limit]         FLOAT (53)     NOT NULL,
    [Dealer]               BIT            NOT NULL,
    [Accounts_Receivables] FLOAT (53)     NOT NULL,
    [Credit_Terms]         NVARCHAR (MAX) NULL,
    [Discount_Scheme]      FLOAT (53)     NOT NULL,
    [Agent]                BIT            NOT NULL,
    [Contacts_Order]       NVARCHAR (MAX) NULL,
    [Contacts_Accounting]  NVARCHAR (MAX) NULL,
    [Telephone_Number]     NVARCHAR (MAX) NULL,
    [Fax_Number]           NVARCHAR (MAX) NULL,
    [Email]                NVARCHAR (MAX) NULL,
    [Rounded_Payment]      BIT            NOT NULL,
    [Usual_Ordered_Item]   NVARCHAR (MAX) NULL,
    [Witholding_Tax]       FLOAT (53)     NOT NULL,
    [Vat_Exemption]        BIT            NOT NULL,
    [Collection_Period]    NVARCHAR (MAX) NULL,
    [Combine_Items]        BIT            NOT NULL,
    [Overpayment_Counter]  FLOAT (53)     NOT NULL,
    [Created_Date]         DATETIME       NOT NULL,
    [Modified_Date]        DATETIME       NULL,
    [IsDeleted]            BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dbo.ClientEntities] PRIMARY KEY CLUSTERED ([Id] ASC)
);

